spring:
  profiles:
    active: local
  application:
    name: hackathon

management:
  server:
    base-path:
  endpoints:
    web:
      exposure:
        include: health,info


springdoc:
  api-docs:
    enabled: true
    # v3/api-docs/ 로 노출
    path: /v3/api-docs
  swagger-ui:
    # UI가 여기서 스펙을 직접 읽어가도록
    url: /v3/api-docs
    path: /swagger-ui